---
name: NewFeatureSuggestion
description: File a bug report
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
    -octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Rapeepat Sripanya
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type-of-request
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Existing Feature
      default: 0
    validations:
      required: false
  - type: dropdown
    id: os-type
    attributes:
      label: What is the OS which you want to suggest?
      options:
        - Windows
        - MacOS
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      value: "Feature details!"
      render: shell